### ISSUE TITLE
Sarcophagus Sealer's artist listed as ???

### ISSUE THREAD

**Issue by fenhl** [fenhl/lore-seeker#1]
The *Ankheret* card [Sarcophagus Sealer](https://loreseeker.fenhl.net/card/ank/31) has art by 酩憲. Lore Seeker lists the card's artist as ???, presumably because both normalize to `_` and MTG JSON has real cards listed with that artist name. I can see four solutions for this:

* Fix the artist credit for the 5 promo cards in MTG JSON (mtgjson/mtgjson#319)
* Fix the normalization algorithm to not mangle CJK characters this badly
* Change the artist credit to a romanized version of the name (Mǐng Xiàn or Huan Ming according to Google)
* Fix the card details page to take artist name directly from the JSON instead of looking it up through the normalization or whatever it is that it's doing right now

**Comment by taw** [comment]
mtg.wtf indexer fixes those 5 Media Insert cards now.

I'll fix the issue one way or another once Global Series Jiang Yanggu & Mu Yanling comes out. It sort of depends on how Gatherer deals with it. If they provide official romanization, I'll just roll with it, otherwise maybe add full CJK support.

**Comment by fenhl** [comment]
Fixed upstream, thanks @taw!
